import Head from "next/head"
import React from "react"
import { Container } from "semantic-ui-react"

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>About</h1>
        <h2>This is an About page.</h2>
        <p>Thanks for coming!</p>
      </Container>
    </>
  )
}
