import Head from "next/head"
import Hero from "../components/Hero"
import AboutMe from "../components/AboutMe"
import SocialLinks from "../components/SocialLinks"
import { Container } from "semantic-ui-react"
import Projects from "../components/Projects"
import Footer from "../components/Footer"

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Jack&apos;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container fluid={true}>
        <Hero />
        <AboutMe />
        <SocialLinks />
        <Projects />
        <Footer />
      </Container>
    </>
  )
}
