import { Container } from "semantic-ui-react"

import AboutMe from "../components/AboutMe"
import FloatingSurvey from "../components/FloatingSurvey"
import Footer from "../components/Footer"
import Head from "next/head"
import Hero from "../components/Hero"
import Projects from "../components/Projects"
import SocialLinks from "../components/SocialLinks"

type Props = {
  buildTimestamp: string
}

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Home | Jack&apos;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Container>
        <AboutMe />
        <SocialLinks />
        <FloatingSurvey>
          <Projects />
        </FloatingSurvey>
      </Container>
      <Footer buildTimestamp={props.buildTimestamp} />
    </>
  )
}

export async function getStaticProps() {
  const date = new Date()
  const buildTimestamp = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()} ${date.getHours()}:${date.getMinutes()}`

  return {
    props: { buildTimestamp: buildTimestamp },
  }
}
