import Head from "next/head"
import Link from "next/link"
import { Container } from "semantic-ui-react"

import AboutMe from "../components/AboutMe"
import FloatingSurvey from "../components/FloatingSurvey"
import Footer from "../components/Footer"
import Hero from "../components/Hero"
import Projects from "../components/Projects"
import SocialLinks from "../components/SocialLinks"
import styles from "../styles/Home.module.scss"

function Navbar() {
  return (
    <>
      <nav className={styles.navbar}>
        <Link href={"/#projects"}>Projects</Link>
        <Link href={"/blogs/"} className={styles.pulse}>
          Blogs
        </Link>
      </nav>
    </>
  )
}

type Props = {
  buildTimestamp: string
}

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Home | Jack&apos;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.page}>
        <Navbar />
        <Hero />
        <Container>
          <AboutMe />
          <SocialLinks />
          <FloatingSurvey>
            <Projects />
          </FloatingSurvey>
        </Container>
        <Footer buildTimestamp={props.buildTimestamp} />
      </div>
    </>
  )
}

export async function getStaticProps() {
  const dateString = new Date().toISOString()
  const buildTimestamp = `${dateString.split('T')[0]} ${dateString.split('T')[1].slice(0, 8)}` // prettier-ignore

  return {
    props: { buildTimestamp: buildTimestamp },
  }
}
